name: Test

on:
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  check-major-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check for major changesets
        id: check_major
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.issue.number;

            console.log('number: ', prNumber);
            console.log('sha: ', context.payload.issue.pull_request.head.sha);
