name: Test

on:
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  check-major-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check for major changesets
        id: check_major
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            let pullRequest = context.payload.pull_request;
      
            if (!pullRequest) {
              // Fetch the pull request data
              const pullRequestData = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: issueNumber,
              });
              pullRequest = pullRequestData.data;
            }

            console.log('number: ', issueNumber);
            console.log('sha: ', pullRequest.head.sha);
